"""First-boot bootstrap: superuser, default external resources, demo content."""
from __future__ import annotations

from pathlib import Path

from sqlalchemy import func, select

from ..core.config import settings
from ..core.logging import get_logger
from ..db.session import SessionLocal
from ..models import Project, Role, User
from . import external as external_service
from . import projects as project_service
from . import sequences as sequence_service
from . import users as user_service

logger = get_logger("geneforge.bootstrap")

SAMPLES_DIR = Path(__file__).resolve().parents[3] / "samples"


def bootstrap(*, with_demo: bool | None = None) -> None:
    """Idempotent: safe to run on every start."""
    db = SessionLocal()
    try:
        admin = db.scalars(select(User).where(User.role == Role.ADMIN.value)).first()
        if admin is None:
            admin = user_service.create_user(
                db,
                email=settings.first_superuser_email,
                username=settings.first_superuser_email.split("@")[0] or "admin",
                password=settings.first_superuser_password,
                full_name="GeneForge Administrator",
                role=Role.ADMIN.value,
            )
            logger.warning(
                "created initial administrator %s — change the password immediately",
                settings.first_superuser_email,
            )
        created = external_service.seed_defaults(db, created_by=admin)
        if created:
            logger.info("seeded %s external resources", created)

        should_demo = with_demo if with_demo is not None else settings.environment != "production"
        if should_demo:
            _seed_demo(db, admin)
        db.commit()
    except Exception:  # noqa: BLE001 - never block startup on bootstrap
        db.rollback()
        logger.exception("bootstrap failed")
    finally:
        db.close()


def _seed_demo(db, admin: User) -> None:
    from ..bio import seqio

    existing = db.scalar(select(func.count()).select_from(Project)) or 0
    if existing:
        return
    if not SAMPLES_DIR.exists():
        return
    project = project_service.create_project(
        db,
        admin,
        name="Demo Cloning Project",
        description="Sample constructs generated by scripts/make_samples.py — safe to delete.",
        tags=["demo", "cloning"],
    )
    imported = 0
    for path in sorted(SAMPLES_DIR.glob("*")):
        if path.suffix.lower() not in (".gb", ".gbk", ".fasta", ".fa", ".dna"):
            continue
        try:
            payload = path.read_bytes()
            for rec in seqio.parse_any(payload, path.name):
                if not rec.sequence:
                    continue
                if db.scalars(
                    select(sequence_service.Sequence).where(
                        sequence_service.Sequence.project_id == project.id,
                        sequence_service.Sequence.name == rec.name,
                    )
                ).first():
                    continue
                sequence_service.create_from_record(db, project, admin, rec)
                imported += 1
        except Exception as exc:  # noqa: BLE001
            logger.warning("could not import demo file %s: %s", path.name, exc)
    logger.info("seeded demo project with %s sequences", imported)
